### ISSUE TITLE
Seeds optimization

### ISSUE THREAD

**Issue by PashkovD** [BaggerFast/Pacman#7]
Why after years, you draw seeds separately? Make buffer for it .
Why you check collision for every seed if you can store seeds per tile and check only current tile?
And main question. Why i write it on English?

**Comment by BaggerFast** [comment]
> Why after years, you draw seeds separately? Make buffer for it . Why you check collision for every seed if you can store seeds per tile and check only current tile? And main question. Why i write it on English?

Make a pull request to fix it
